apiVersion: v1
kind: Service
metadata:
  name: dmz-service
spec:
  type: NodePort
  selector:
    app: dmz
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
      nodePort: 30443